### ISSUE TITLE
+Имя переменной `b` ни о чём не говорит+

### ISSUE THREAD

**Issue by vadimlarionov** [aksesss/lab4#1]
https://github.com/aksesss/laba3_ready/blob/431dddf78839269a821ee6f42e6223fe7477d1f4/librip/gens.py#L9-L17

Переменная `b` понятна только тебе.  
Думаю, можно обойтись и без неё. Сейчас в коде ты проверяешь, что `item_dict` содержит все `args`. На мой взгляд, это не совсем верно. 
```python
goods = [
    {'title': 'iPhone X', 'color': 'black'},
    {'title': 'Ковер', 'price': 2000, 'color': 'green'},
]

print(list(field(goods, 'title', 'price')))
```
Выведет `[{'title': 'Ковер', 'price': 2000}]`. Давай сделаем так, чтобы `iPhone` тоже попал в выдачу

**Comment by aksesss** [comment]
b --> item_is_not_None

**Comment by aksesss** [comment]
Моя программа выведет айфон если него нет цены

**Comment by aksesss** [comment]
if len(args) == 1:
        for item_dict in items_list:
            if item_dict[args[0]] is not None:
                yield item_dict[args[0]]
    else:
        for item_dict in items_list:
            dictionary = {}
            for arg in args:
                if item_dict.get(arg) is not None:
                    dictionary[arg] = item_dict.get(arg)

            if dictionary != {}:
                yield dictionary
            else:
                continue
