### ISSUE TITLE
+Комментарий без смысла. Попробуем typing?+

### ISSUE THREAD

**Issue by vadimlarionov** [aksesss/lab4#4]
https://github.com/aksesss/laba3_ready/blob/431dddf78839269a821ee6f42e6223fe7477d1f4/librip/gens.py#L35
Комментарии лучше если и писать, то по делу. В твоём случае хорошо бы подошёл python docstring. Вот пример http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
По docstring-ам есть утилиты, которые автоматически генерируют документацию. Плюс можно на методе в Pycharm нажать `ctrl+q` и увидеть документацию.

Если хочешь явно указать тип, то можешь поставить python 3.6 и использовать [typing](https://docs.python.org/3/library/typing.html).
Предлагаю попробовать typing.

**Comment by aksesss** [comment]
убрал)
