### ISSUE TITLE
+-Сделаем итератор лучше!

### ISSUE THREAD

**Issue by vadimlarionov** [aksesss/lab4#9]
## Дублирование кода
https://github.com/aksesss/laba3_ready/blob/431dddf78839269a821ee6f42e6223fe7477d1f4/librip/iterators.py#L14-L28
Смотри, у тебя строки 18-22 и 24-28 совпадают. Значит они не зависят от условия и можно их вынести из `if-else`.

## Неиспользуемый код
Зачем тебе это? Можно удалить.
https://github.com/aksesss/laba3_ready/blob/431dddf78839269a821ee6f42e6223fe7477d1f4/librip/iterators.py#L16

## Сделаем код эффективнее
Ты используешь список, чтобы запоминать элементы, которые уже были. Замени список на множество (set). Множество отличается от списка тем, что оно хранит только уникальные элементы, без дублей. Т.е. можно будет всегда вызывать `unique_items.add(element)`. И самое главное: чтобы проверить, есть ли элемент в списке, нужно обойти весь список. Множество отвечает сразу (асимптотическая сложность - O(1)).

И получится круто!
P.S. Тело метода `is_unique` в идеале будет содержать 4 строки.

**Comment by vadimlarionov** [comment]
Для сравнения, твой код итератора, который проверяет уникальность на основе списка, у меня работает `0.04774`.
На основе множества - `0.01571`. В 3 раза быстрее получилось.

**Comment by aksesss** [comment]
q
